name: transformer_utils
version: 0.2.22
description: Utilities relating to code generation, Dart analyzer, logging, etc. for use in Dart builders.
homepage: https://github.com/Workiva/dart_transformer_utils

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  analyzer: '>=5.0.0 <8.0.0'
  build:  ^2.0.3
  collection: ^1.15.0
  path: ^1.8.0
  source_span: ^1.8.1

dev_dependencies:
  test: ^1.16.0
