name: transformer_utils
version: 0.2.16
description: Utilities relating to code generation, Dart analyzer, logging, etc. for use in Dart builders.
homepage: https://github.com/Workiva/dart_transformer_utils

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  analyzer: '>=0.41.0 <2.0.0'
  build: '>=1.2.2 <3.0.0'
  path: ^1.6.4
  source_span: ^1.5.5

dev_dependencies:
  dependency_validator: ^3.0.0
  test: ^1.15.7
