name: transformer_utils
version: 0.2.17
description: Utilities relating to code generation, Dart analyzer, logging, etc. for use in Dart builders.
homepage: https://github.com/Workiva/dart_transformer_utils

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: '>=1.7.2 <3.0.0'
  build:  ^2.0.3
  collection: ^1.15.0
  path: ^1.8.0
  source_span: ^1.8.1

dev_dependencies:
  dependency_validator: ^3.0.0
  test: ^1.16.0