name: transformer_utils
version: 0.2.8
description: Utilities relating to code generation, Dart analyzer, logging, etc. for use in Pub transformers.
homepage: https://github.com/Workiva/dart_transformer_utils

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: '>=1.7.0 <3.0.0'
  build: ^2.0.3
  path: ^1.8.0
  source_span: ^1.8.1
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
#  dart_dev: ^3.0.0
#  dart_style: ^1.3.3
#  dependency_validator: ^1.4.1
  test: ^1.17.10
