name: transformer_utils
version: 0.2.10
description: Utilities relating to code generation, Dart analyzer, logging, etc. for use in Pub transformers.
homepage: https://github.com/Workiva/dart_transformer_utils

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  analyzer: ">=0.39.0 <0.42.0"
  build: ^1.2.2
  path: ^1.6.4
  source_span: ^1.5.5

dev_dependencies:
  dart_dev: ^3.0.0
  dart_style: ^1.3.3
  dependency_validator: ^1.4.1
  test: ^1.15.7
