name: transformer_utils
version: 0.2.3
description: Utilities relating to code generation, Dart analyzer, logging, etc. for use in Pub transformers.
authors:
  - Workiva UI Platform Team <uip@workiva.com>
  - Workiva Client Platform Team <cp@workiva.com>
  - Greg Littlefield <greg.littlefield@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
homepage: https://github.com/Workiva/dart_transformer_utils

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  analyzer: ^0.39.1
  build: ^1.2.2
  path: ^1.6.4
  source_span: ^1.5.5

dev_dependencies:
  build_runner: ^1.7.2
  build_test: ^0.10.10
  build_web_compilers: ^2.7.1
  dart_dev: ^3.0.0
  dart_style: ^1.3.3
  dependency_validator: ^1.4.1
  test: ^1.9.3
