name: Dart CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [ 2.19.6, stable ]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Validate dependencies
        run: dart pub global activate dependency_validator && dart pub global run dependency_validator
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
        if: ${{ matrix.sdk == 'stable' }}
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: dart test
      - uses: anchore/sbom-action@v0
        with:
          path: ./
          format: cyclonedx-json
